name: Application Backend Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Get version"
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build Endurist Web API Image
      run: docker build . --file backend/src/Endurist.Web/Dockerfile --tag marzavin/endurist-api:${{ env.RELEASE_VERSION }}

    - name: Tag Endurist Web API Image as 'latest'
      run: docker tag marzavin/endurist-api:${{ env.RELEASE_VERSION }} marzavin/endurist-api:latest

    - name: Build Endurist Background Worker Image
      run: docker build . --file backend/src/Endurist.Worker/Dockerfile --tag marzavin/endurist-worker:${{ env.RELEASE_VERSION }}

    - name: Tag Endurist Background Worker Image as 'latest'
      run: docker tag marzavin/endurist-worker:${{ env.RELEASE_VERSION }} marzavin/endurist-worker:latest

    - name: Docker Login
      run: docker login -u="${{ secrets.DOCKER_LOGIN }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: Push Endurist Web API Image
      run: docker image push marzavin/endurist-api:${{ env.RELEASE_VERSION }}

    - name: Push Endurist Web API Image (latest)
      run: docker image push marzavin/endurist-api:latest

    - name: push Endurist Background Worker Image
      run: docker image push marzavin/endurist-worker:${{ env.RELEASE_VERSION }}

    - name: push Endurist Background Worker Image (latest)
      run: docker image push marzavin/endurist-worker:latest
